### ISSUE TITLE
SQLite upload speed is prohibitive

### ISSUE THREAD

**Issue by FloodHydrology** [khondula/rodm2#14]
It took ~7.4 hrs to upload ~1 month of data from 15 PT's into the SQLite database.

**Comment by khondula** [comment]
I will test out wrapping in [explicit transactions](https://www.sqlite.org/lang_transaction.html) or using [prepared queries](http://sqlite.org/c3ref/prepare.html).

thankfully postgres connection inserted the same amount of data in just over 1 minute!

**Comment by khondula** [comment]
same operation ~10k rows took 15 seconds in desktop rstudio, 8 mins in home directory on rstudio server, and 2.5 hrs in nfs on rstudio server

**Comment by khondula** [comment]
begin and end transaction statements seem to do the trick. same operation that took 2.5 hrs down to 16 seconds.

**Comment by khondula** [comment]
seems to have been an issue just with rstudio server but not sure what the issue is. added begin and end transaction statements as workaround.
