### ISSUE TITLE
describe_sites function

### ISSUE THREAD

**Issue by khondula** [khondula/rodm2#2]

**Comment by khondula** [comment]
done for sqlite for one site. should modify describe_site_geom to be able to accept a column from sf object that has site code names in it.

**Comment by FloodHydrology** [comment]
Function should be implemented for postgreSQL db's as well.  :)

**Comment by khondula** [comment]
postgres version of non-geom site 2c13d1bbc8b55d42a9c07061f41024ecbb4c9e3d

**Comment by khondula** [comment]
only include non geometry sites upload for now.
